### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by burovytskyi** [hmarr/chrome-detect-font#12]
Hello.  Please indicate the license under which your extension code is distributed

**Comment by hmarr** [comment]
It's [MIT](https://github.com/hmarr/chrome-detect-font/blob/8c18adf2f558d117eac421065c62f556c9535069/package.json#L5). Just [added](https://github.com/hmarr/chrome-detect-font/commit/8c18adf2f558d117eac421065c62f556c9535069) a LICENSE file so it's clearer.
